apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  replicas: 4
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: app-container
          image: golang:1.21
          command: ["tail", "-f", "/dev/null"]
        - name: postgres-container
          image: postgres:16
          command: ["tail", "-f", "/dev/null"]

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
spec:
  project: default
  source:
    repoURL: https://github.com/okuda-seminar/Twitter-Clone.git
    targetRevision: main
    path: kustomize/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

